package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Usuario
 */
public class GameView extends javax.swing.JFrame {

    /**
     * Creates new form BoardView
     */
    public GameView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTblBoard = new javax.swing.JTable();
        jBtnFlipBoard = new javax.swing.JButton();
        JLblScore = new javax.swing.JLabel();
        jLblState = new javax.swing.JLabel();
        jLblBlackMoves = new javax.swing.JLabel();
        jLblWhiteMoves = new javax.swing.JLabel();
        jLblTurn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 444));
        setResizable(false);

        jTblBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblBoard.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTblBoard.setAutoscrolls(false);
        jTblBoard.setRowSelectionAllowed(false);
        jTblBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblBoardMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTblBoard);

        jBtnFlipBoard.setText("Flip Board");

        JLblScore.setText("Score");

        jLblState.setText("State");

        jLblBlackMoves.setText("BlackMoves");

        jLblWhiteMoves.setText("WhiteMoves");

        jLblTurn.setText("Turn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblState)
                    .addComponent(jBtnFlipBoard)
                    .addComponent(JLblScore)
                    .addComponent(jLblBlackMoves)
                    .addComponent(jLblWhiteMoves)
                    .addComponent(jLblTurn))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jBtnFlipBoard)
                .addGap(31, 31, 31)
                .addComponent(JLblScore)
                .addGap(18, 18, 18)
                .addComponent(jLblState)
                .addGap(18, 18, 18)
                .addComponent(jLblBlackMoves)
                .addGap(18, 18, 18)
                .addComponent(jLblWhiteMoves)
                .addGap(18, 18, 18)
                .addComponent(jLblTurn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTblBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblBoardMouseClicked
        row = jTblBoard.rowAtPoint(evt.getPoint());
        col = jTblBoard.columnAtPoint(evt.getPoint());
    }//GEN-LAST:event_jTblBoardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameView().setVisible(true);
            }
        });
    }

    public JTable getjTblBoard() {
        return jTblBoard;
    }

    public JButton getjBtnFlipBoard() {
        return jBtnFlipBoard;
    }

    public int getRow() {
        return row;
    }

    public int getCol() {
        return col;
    }

    public JLabel getJLblScore() {
        return JLblScore;
    }

    public JLabel getjLblState() {
        return jLblState;
    }

    public JLabel getjLblBlackMoves() {
        return jLblBlackMoves;
    }

    public JLabel getjLblWhiteMoves() {
        return jLblWhiteMoves;
    }

    public JLabel getjLblTurn() {
        return jLblTurn;
    }
    
    private int row = 0;
    private int col = 0; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblScore;
    private javax.swing.JButton jBtnFlipBoard;
    private javax.swing.JLabel jLblBlackMoves;
    private javax.swing.JLabel jLblState;
    private javax.swing.JLabel jLblTurn;
    private javax.swing.JLabel jLblWhiteMoves;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblBoard;
    // End of variables declaration//GEN-END:variables
}
